on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing Serverless Action
    steps:
    - name: Serverless Action
      id: sls
      uses: serverless/azure-build-task@release-v0.1.0
      with:
        yamlFile: 'serverless.yml'
        